spring:
  application:
    name: jwt

  datasource:
    url: jdbc:mysql://localhost:3306/userdatabase?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database:
      platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: IMUpcnSs8Azi6NmrkSWvIOlOIVgYseKWAdQQyyLSGGC0nfeII6e4+77kf2NIDVIDav6MF6H/6nbo19o3TiGXxg==
  expiration: 8400000

admin:
  username: admin
  email: admin@jwt.com
  mobile: "9000090000"
  password: admin
